components/rpc/invoker/mosn/mosninvoker.go
components/rpc/invoker/mosn/mosninvoker_test.go

When Invoke method panic, return error instead of return nil
Fixes https://github.com/mosn/layotto/issues/114
```release-note
```

return error when panic

---

go.mod
sdk/go-sdk/go.mod
sdk/go-sdk/go.sum

upgrade dep
Fixes #
```release-note
```

upgrade dep

---

components/lock/etcd/etcd_lock.go
components/lock/etcd/etcd_lock_test.go
configs/config_lock_etcd.json
docs/_sidebar.md
docs/en/component_specs/lock/common.md
docs/en/component_specs/lock/etcd.md
docs/zh/_sidebar.md
docs/zh/component_specs/lock/common.md
docs/zh/component_specs/lock/etcd.md

Change the configuration item `keyPrefix` into `keyPrefixPath` in etcd lock
Fixes #143 
```release-note
```

change the configuration item `keyPrefix` into `keyPrefixPath` in etcd lock

---

.gitignore

Ignore the build result in case of add the build result to the repository.
Fix issue #218

Ignore the build result

---

docs/en/start/wasm/start.md
docs/zh/start/wasm/start.md

The rendered code block of markdown is broken, add a blank line before
the code block can fix it.
Fixes: #228

fix broken markdown in docs

---

Makefile
configs/config_integration_redis_etcd.json
spec/proto/runtime/v1/runtime.proto

Add integration config for the local e2e test cases
Fixes #
```release-note
```

improve: Fixed int64 overflow problems on JavaScript

---

cmd/layotto/main.go
configs/config_in_memory.json
demo/pubsub/in-memory/in-memory.go

Add in-memory pubsub component and demo client
Fixes #67
```release-note
```

feat: in-memory pubsub component

---

sdk/java-sdk/README-zh.md
sdk/java-sdk/README.md
sdk/java-sdk/examples/pom.xml
sdk/java-sdk/examples/src/main/java/io/mosn/layotto/examples/file/File.java
sdk/java-sdk/pom.xml
sdk/java-sdk/sdk/pom.xml
sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/FileRuntime.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/FileInfo.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMetaRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMeteResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileResponse.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTest.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTestWithRealServer.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/mock/MyFileService.java

Including PutFile, GetFile, DelFile, ListFile

feat(java-sdk): java sdk support File API

---

sdk/java-sdk/README-zh.md
sdk/java-sdk/README.md
sdk/java-sdk/examples/pom.xml
sdk/java-sdk/examples/src/test/java/io/mosn/layotto/examples/file/File.java
sdk/java-sdk/pom.xml
sdk/java-sdk/sdk/pom.xml
sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/RuntimeClientGrpc.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/FileRuntime.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/DelFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/FileInfo.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMetaRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/GetMeteResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/ListFileResponse.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileRequest.java
sdk/java-sdk/sdk/src/main/java/spec/sdk/runtime/v1/domain/file/PutFileResponse.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTest.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/FileTestWithRealServer.java
sdk/java-sdk/sdk/src/test/java/io/mosn/layotto/v1/mock/MyFileService.java

support listFile, GetFile, PutFile, DelFile, GetFileMeta

feat(java-sdk): java sdk support File API (#325)

---

components/lock/zookeeper/zookeeper_lock_test.go

fix zk lock ut fail. New version of gomock requires  the expected call times  must equals the real call times.
Fixes #363 
```release-note
```

fix zk lock ut

---

configs/config_apollo.json
configs/config_apollo_health.json
configs/config_apollo_health_mq.json
configs/config_file.json
configs/config_integration_redis_etcd.json
configs/runtime_config.json
configs/wrong/config_apollo_health.json
docs/en/component_specs/state/common.md
docs/en/start/configuration/start.md
docs/zh/component_specs/file/common.md
docs/zh/component_specs/state/common.md
docs/zh/design/actuator/grpc-design-doc.md
docs/zh/design/file/file-design.md
docs/zh/start/configuration/start.md
docs/zh/start/file/minio.md
pkg/runtime/config.go
pkg/runtime/config_test.go
pkg/runtime/state/compatibility.go
pkg/runtime/state/compatibility_test.go

The configuration schema in `config.json` is changed: 
- `config_stores` -> `config_store`
- `files` -> `file`
- Change default state prefix strategy from `appid` to `none`
The previous default strategy `appid` will change the original key to `appid||key`. If users forget to add a strategy in their `config.json`, Layotto will modify all the keys written to backend DB, which is dangerous and pollutes the existing data.
So I think it's more appropriate to change the default strategy to `none`.
Fixes #
```release-note
The configuration schema in `config.json` is changed: 
- `config_stores` -> `config_store`
- `files` -> `file`
- Change default state …
```

feat(config.json): schema change

---

demo/rpc/dubbo_json_rpc/dubbo_json_client/client.go
docs/en/start/rpc/dubbo_json_rpc.md
docs/zh/start/rpc/dubbo_json_rpc.md

fix dubbo demo
Fixes #458 
With this operation, I can successfully run the dubbo demo and receive the response.
```NONE
```

fix: dubbo demo fails (#458)

---

components/configstores/apollo/configstore.go
components/pkg/actuators/actutors_test.go
components/pkg/actuators/indicator.go
components/pkg/actuators/indicator_test.go
components/sequencer/in-memory/in_memory_sequencer.go

- don't register apollo actuator when no apollo component configurated 
- add actuator for in-memory sequencer component;
Fixes #462 
```release-note
```

fix: don't register apollo actuator when no apollo component configurated 

---

.github/workflows/layotto-ci.yml
.github/workflows/layotto-release.yml
go.mod
go.sum
make/golang.mk
pkg/grpc/default_api/api_pubsub.go

ci: reopen unit test checks and fix fatal
Test cases in below packages:
@echo "===========> Run unit test in sdk/go-sdk"
@echo "===========> Run unit test in components"
@echo "===========> Run unit test in pkg"
@echo "===========> Run unit test in diagnostics"
resolve: https://github.com/mosn/layotto/issues/529

ci: reopen unit test checks and fix fatal

---

.github/workflows/layotto-release.yml

Add a few steps in Layotto Release Pipeline so that binaries are auto uploaded to Release page when a new version is released.
Fixes #563 
```release-note
NONE
```

ci: automatically upload binary files when releasing new version

---

Makefile
docs/en/development/commands.md
docs/zh/development/commands.md

Run `make license` to add licnese headers for all code files, with docker
Fixes #
```release-note
```

chore(make): `make license` to add licnese headers for all code files.

---

components/custom/registry.go
pkg/runtime/runtime.go
sdk/go-sdk/client/client_test.go

fix legacy issues of #549
Fixes #
```release-note
```

fix: fix legacy issues of #549

---

pkg/grpc/default_api/api_configuration.go

Fixes #613
```release-note
```

fix: configuration API returns wrong app_id

---

cmd/layotto/main.go
cmd/layotto_multiple_api/main.go
etc/script/test-quickstart.sh

Fixes #643 
```release-note
```

fix: jaeger tracer nil pointer

---

components/file/s3/qiniu/qiniu_oss_client_test.go
components/file/s3/qiniu/qiniu_oss_test.go
components/go.mod
components/go.sum
go.sum

在`components/file/s3/qiniu`目录的单测中，使用到http.Get方法向`example.com`发起请求，导致部分地区无法访问该域名时，会出现单测无法通过的情况。目前通过对http的请求进行mock，来避免发起真实的请求。
Fixes  #528

fix: Unit tests fail in component package

---

configs/config_trace_jaeger.json
diagnostics/jaeger/grpc_tracer.go
docs/zh/start/trace/jaeger.md

I found an error in jaeger's json that caused the code to parse incorrectly, In this pr I delete the useless.

fix: jaeger code error

---

docs/zh/start/api_plugin/helloworld.md

What this PR does:
Which issue(s) this PR fixes:
Fixes https://github.com/mosn/layotto/issues/680
Special notes for your reviewer:
翻译了API Plugin的快速入门英文文档
Does this PR introduce a user-facing change?:

docs: Translate the api-plugin quickstart into Chinese

---

make/common.mk
make/golang.mk

I spent some time telling @dzdx how to fix the CI error in https://github.com/mosn/layotto/pull/676 . 
It's not cool.
So I think we should make error message in "🌈 Go Style Check" more readable
Fixes #
```release-note
```

ci: make error message in "🌈 Go Style Check" more readable

---

components/lock/zookeeper/zookeeper_lock.go
components/lock/zookeeper/zookeeper_lock_test.go

fix ut unstable of zookeeper lock, wait connection to close. 
Fixes #682 
```release-note
```

fix: ut unstable of zk lock

---

docs/zh/_sidebar.md
docs/zh/development/label-spec.md
docs/zh/operation/local.md

add docs including:
- guide for local development
see https://github.com/mosn/layotto/issues/713#issuecomment-1182664149
- label spec
https://github.com/mosn/layotto/issues/653
Fixes https://github.com/mosn/layotto/issues/653
```release-note
```

docs: add guide for local development & add label spec

---

.github/dead_link_check_config.json

Let the deadlink checker ignores https://docs.buf.build/
Fixes the CI error in #736 
```release-note
```

ci: deadlink checker ignores https://docs.buf.build/

---

docs/zh/operation/local.md

improve dev guide
Fixes #
```release-note
```

docs: improve dev guide

---

sdk/go-sdk/client/client.go

OSS go sdk
Fixes #
```release-note
```

feat(sdk): OSS go sdk

---

components/rpc/invoker/mosn/mosninvoker.go

Signed-off-by: Xunzhuo <bitliu@tencent.com>
Incorrect conversion of an integer with architecture-dependent bit size from `strconv.Atoi` to a lower bit size type int32 without an upper bound check.

fix: Incorrect conversion between integer types

---

.github/workflows/dead-link-checker.yaml
.github/workflows/stale.yml

Signed-off-by: Xunzhuo <bitliu@tencent.com>
chore: set deadlink validation to schedule, move out of PRs

chore: set deadlink validation to schedule, move out of PRs

---

go.mod
go.sum
pkg/grpc/delay_queue/server.go
pkg/grpc/email/server.go
pkg/grpc/phone/server.go

Use copier to convert structs
I used to use json marshal/unmarshal to convert requests, which is bad :(
Fixes #
```release-note
```

feat: use copier to convert structs

---

.golangci.yml

Warning from command `golangci-lint run ./...`
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.

chore: remove linters which is deprecated

---

docs/en/start/secret/start.md
docs/zh/start/secret/start.md

Add java sdk secret demo docs.

docs: secret demo

---

docs/en/start/lock/start.md
docs/zh/start/lock/start.md

fix: Revert "feat: add js document"

---

configs/config.json
configs/config_apollo.json
configs/config_consul.json
configs/config_file.json
configs/config_file_qiniu_oss.json
configs/config_file_tencentcloud_oss.json
configs/config_integrate_test.json
configs/config_mongo.json
configs/config_oss.json
configs/config_redis.json
configs/config_ref_example.json
configs/config_snowflake.json
configs/config_standalone.json
configs/config_trace_jaeger.json
configs/config_trace_skywalking.json
configs/config_trace_zipkin.json
configs/config_zookeeper.json
configs/runtime_config.json
demo/faas/config.json
demo/rpc/dubbo_json_rpc/example.json
demo/rpc/http/example.json

I just took the task of integrating istio 1.10 #664 and fixed #700  by the way
Fixes #700

fix: add xds v3 default config

---

README.md
docs/en/start/wasm/start.md
docs/zh/start/wasm/start.md
pkg/wasm/dispatch.go
pkg/wasm/factory.go
pkg/wasm/factory_test.go

fix error when running WASM quickstart
Fixes #838 
```release-note
```

fix: error when running WASM quickstart

---

docs/en/development/commands.md
docs/zh/development/commands.md
make/golang.mk

1. Fix the problem of `make format`  not working well with multi go path.
2. Update docs in "commands guide". 
**Which issue(s) this PR fixes**:  #896
Fixes #
I found that gopath was not registered in the environment variables by default, so I still used the method provided in the original text in the issue to solve this bug
**Does this PR introduce a user-facing change?**: None

fix: make format and update command guide docs

---

make/golang.mk

make unit test failed info more clear in ci
Fixes #646
```release-note
NONE
```

feat: unit test failed info more clear in ci

---

docs/api/v1/sms.html
spec/proto/extension/v1/sms/sms.pb.go
spec/proto/extension/v1/sms/sms.proto

modify sms api proto and generate its docs
```release-note
```

feat: modify sms api proto

---

docs/zh/start/uds/start.md

Add java-sdk uds demo doc
```release-note
```

docs: Update start.md

---

.github/workflows/layotto-ci.yml
.github/workflows/layotto-release.yml

Fixes #1005 
```release-note
```

fix: include checkout step for package laytto injector helm chart

---

.github/dead_link_check_config.json
docs/_sidebar.md
docs/en/operation/sidecar_injector.md
docs/zh/_sidebar.md
docs/zh/operation/sidecar_injector.md
pkg/grpc/default_api/api_lock_test.go
pkg/injector/patcher/sidecar_patcher_test.go
pkg/injector/service/handle.go

add ut and docs for the sidecar injector
Fixes #
```release-note
```

chore: add ut and docs for sidecar injector

---

README.md

Github Action Bot detected the issue body's language is not English, translate it automatically
---
Fixes #
```release-note
```
<details><summary>原文</summary>
Fixes #
```release-note
```</details>

fix: README问题图片修复||fix: README problem image fix

---

pkg/grpc/dapr/dapr_api.go
pkg/grpc/extension/s3/s3.go

Because there is a performance loss in the serialization of prtobuf, in order to reduce the performance loss of grpc in the oss scenario, the data size of each file transfer is increased to reduce the number of transmissions.

feat: change getobject default size from 100kb to 1M

---

pkg/grpc/dapr/dapr_api_pubsub.go
pkg/grpc/default_api/api_pubsub.go

Fix problematic error returns
Fixes #
```release-note
Fix problematic error returns
```

fix: Fix problematic error returns
