mosn/layotto

- docs/en/start/pubsub/start.md
- docs/zh/start/pubsub/start.md
> fix wrong links

- docs/en/design/pubsub/layotto-pubsub-and-compability-with-dapr.md
- docs/en/start/pubsub/start.md
- docs/zh/design/pubsub/layotto-pubsub-and-compability-with-dapr.md
- docs/zh/start/pubsub/start.md
> Fix pubsub doc

- README-ZH.md
- README.md
> remove wechat

- README-ZH.md
- README.md
- docs/en/design/configuration/configuration-api-with-apollo.md
> improve design docs

- go.mod
- go.sum
fix m1 compile error
Fixes #68 
```release-note
```
> fix m1 compile error

- .github/workflows/github-actions.yml
- README-ZH.md
- README.md
> add motivation and FAQ

- components/rpc/invoker/mosn/channel/httpchannel.go
- components/rpc/invoker/mosn/channel/httpchannel_test.go
Fixes #77 
```release-note
```
> fix fasthttp uri parse

- docs/en/start/actuator/start.md
- docs/en/start/network_filter/tcpcopy.md
- docs/zh/start/network_filter/tcpcopy.md
/kind cleanup
Fixes #
```release-note
NONE
```
> fix broken link

- demo/rpc/http/echoclient/echoclient.go
- demo/rpc/http/example.json
> fix bug issue #77

- docs/en/design/actuator/actuator-design-doc.md
The original file encoding is ISO-8859-1 and some(Chinese) characters are invalid. This PR will remove the invalid characters and replaced them with the correct ASCII characters.
Fixes #
```release-note
```
> remove invalid characters

- README.md
fix grammar issues in README
Fixes #
```release-note
```
> fix grammar issues

- docs/zh/start/configuration/start-apollo.md
fix build error by network error
改善某些网址被屏蔽的情况下构建失败的场景
Fixes #
添加代理解决
```release-note
```
> improve docs

- README.md
- docs/en/README.md
- docs/zh/README.md
- docs/zh/development/contributing-doc.md
- docs/zh/start/state/start.md
replace website url
Fixes #
```release-note
```
> replace website url

- docs/en/README.md
remove redundent description in README
Fixes #
```release-note
```
> remove redundent description in README

- demo/wasm/code/assemblyscript/asconfig.json
- demo/wasm/code/assemblyscript/assembly/index.ts
- demo/wasm/code/assemblyscript/assembly/tsconfig.json
- demo/wasm/code/assemblyscript/index.js
- demo/wasm/code/assemblyscript/package-lock.json
- demo/wasm/code/assemblyscript/package.json
- demo/wasm/config.json
- docs/en/start/wasm/start.md
- docs/zh/start/wasm/start.md
> add assemblyscript wasm demo

- components/configstores/configstore.go
- go.mod
- go.sum
- pkg/grpc/api.go
- pkg/grpc/api_test.go
fix configuration API ut error
Fixes #
```release-note
```
> fix configuration API ut error

- docs/zh/blog/mosn-subproject-layotto-opening-a-new-chapter-in-service-grid-application-runtime/index.md
add introduction blog
Fixes #
```release-note
```
> add introduction blog.md

- docs/_sidebar.md
- docs/en/api_reference/actuator/actuator.md
- docs/en/api_reference/state/reference.md
- docs/en/component_specs/lock/common.md
- docs/en/component_specs/state/common.md
- docs/en/start/state/start.md
- docs/zh/_sidebar.md
- docs/zh/api_reference/actuator/actuator.md
- docs/zh/api_reference/state/reference.md
- docs/zh/component_specs/lock/common.md
- docs/zh/component_specs/state/common.md
- docs/zh/start/state/start.md
- spec/proto/runtime/v1/runtime.proto
1. Add api reference document for State API.
See docs/en/api_reference/state/reference.md
and
docs/zh/api_reference/state/reference.md
2. add more comments for State API in runtime.proto
3. add component spec doc for State API
```release-note
```
> Add api reference for State API

- docs/_sidebar.md
- docs/en/api_reference/sequencer/reference.md
- docs/en/start/configuration/start-apollo.md
- docs/en/start/lock/start.md
- docs/en/start/pubsub/start.md
- docs/en/start/sequencer/start.md
- docs/en/start/state/start.md
- docs/zh/_sidebar.md
- docs/zh/start/configuration/start-apollo.md
- docs/zh/start/lock/start.md
- docs/zh/start/pubsub/start.md
- docs/zh/start/sequencer/start.md
- docs/zh/start/state/start.md
1. Add english version of sequencer API docs
2. improve quickstarts for other APIs
Fixes #
```release-note
```
> Add english version of sequencer API docs

- sdk/go-sdk/client/client.go
- sdk/go-sdk/client/client_test.go
- sdk/go-sdk/client/invoke.go
- sdk/go-sdk/client/invoke_test.go
- sdk/go-sdk/client/pubsub.go
- sdk/go-sdk/client/pubsub_test.go
Add more features for go sdk. Add those sdk API in Dapr go-sdk
Fixes #159
```release-note
```
> add more features for go sdk

- README.md
- docs/en/README.md
- docs/zh/README.md
> Revert "add feature list doc"

- README.md
- docs/en/README.md
- docs/zh/README.md
add description for wasm in readme
Fixes #
```release-note
```
> add description for wasm in readme

- docs/en/design/lock/lock-api-design.md
improve description for lock design (again)
Fixes #
```release-note
```
> improve description for lock design (again)

- docs/zh/design/lock/lock-api-design.md
fix incorrect md syntax
Fixes #187
> fix incorrect md syntax

- docs/_sidebar.md
- docs/en/development/contributing-doc.md
- docs/en/development/developing-api.md
- docs/en/development/developing-component.md
translate a couple of development docs for issue #202 . for example: developing-api.md, eveloping-component.md and contributing-doc.md.
Fixes #
```release-note
```
> Translate chinese documents into english for issue #202

- components/configstores/apollo/change_listener.go
- pkg/grpc/api.go
- sdk/go-sdk/client/client_test.go
- sdk/go-sdk/client/configuration.go
- sdk/go-sdk/client/goroutine.go
- sdk/go-sdk/client/goroutine_test.go
in `pkg` and `sdk` replace `go func` with `utils.GoWithRecover`
Fixes #197
```release-note
```
> style: replace `go func` with `utils.GoWithRecover`

- .gitignore
Ignore the redis demo binary
Fix issue #218
> Ignore the redis demo binary

- docs/en/start/wasm/start.md
- docs/zh/start/wasm/start.md
fix errors in wasm quick start doc
Fixes #222
> fix errors in wasm quick start doc

- README.md
- docs/en/README.md
add talks presented in KubeCon + CloudNativeCon NA 2021 and OpenInfra Asia 2021
Fixes #
```release-note
```
> add English presentations

- sdk/java-sdk/pom.xml
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/package-info.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/AbstractLayottoReactorClient.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClient.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClientBuilder.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/client/reactor/LayottoReactorClientGrpc.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/BooleanProperty.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/GenericProperty.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/IntegerProperty.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/Properties.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/Property.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/config/StringProperty.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/CloudEvent.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloRequest.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/SayHelloResponse.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockRequest.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/TryLockResponse.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockRequest.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/domain/UnlockResponse.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/exceptions/LayottoError.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/exceptions/LayottoException.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/DefaultObjectSerializer.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/LayottoObjectSerializer.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/serializer/ObjectSerializer.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/utils/GrpcWrapper.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/utils/NetworkUtils.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/value/Headers.java
- sdk/java-sdk/src/main/java/io/mosn/layotto/v1/value/LayottoApiProtocol.java
- sdk/java-sdk/src/main/java/spec/sdk/reactor/v1/domain/core/invocation/HttpExtension.java
Add reactor-java-sdk for layotto.
The code is mainly from dapr, and adjusted in conjunction with layotto.
See https://github.com/mosn/layotto/issues/206
> feat: create reactor-java-sdk refer to dapr-java-sdk

- components/lock/redis/standalone_redis_lock.go
Remove unused `replicas` in redis standalone component 
Fixes #
```release-note
```
> fix: remove unused `replicas` field

- .gitmodules
- sdk/dotnet-sdk/README.md
- sdk/js-sdk/README.md
delete gitmodules;
add README and links to dotnet and js sdk instead.
I just found that git submodules can only be linked to a fixed commit id. It cannot link to the latest commit of a branch.
So I decide to use a README instead
```release-note
```
> chore(sdk): Add links to dotnet and js sdk

- demo/file/client.go
change demo bucket name to args
Fixes #
```release-note
```
> add bucket name as args for demo

- sdk/java-sdk/sdk/src/main/java/io/mosn/layotto/v1/grpc/PubsubConverter.java
- sdk/java-sdk/sdk/src/main/java/spec/proto/runtime/v1/AppCallbackProto.java
- spec/proto/runtime/v1/appcallback.proto
Add metadata field to TopicEventRequest
Fixes #
```release-note
```
> topic event request add metadata field

- components/lock/lock_store.go
- sdk/java-sdk/README-zh.md
- sdk/java-sdk/README.md
add more description in java sdk doc;
improve comments in lock component;
Fixes #
```release-note
```
> doc(java-sdk): add more description in java sdk doc

- cmd/layotto/main.go
- configs/config_in_memory.json
- demo/pubsub/common/client/publish_client.go
- demo/pubsub/common/server/subscribe_server.go
Modify in-mem state component name ;
Add demos for in-mem pubsub;
Fixes #
```release-note
```
> chore: modify in-mem state component name and add demos

- docs/zh/_sidebar.md
- docs/zh/video/a-new-chapter-in-service-mesh-application-runtime.md
- docs/zh/video/inject-soul-into-sidecar.md
> add share videos

- codecov.yml
- components/lock/consul/consul_lock.go
- components/lock/consul/consul_lock_task.go
- components/lock/consul/consul_lock_test.go
- move the nondeterministic code in consul lock to a new file:
After that ,  we can ignore the test coverage rate of it:
- add ut for consul lock
Fixes #
```release-note
```
> test: improve test cases for consul lock 

- docs/_sidebar.md
- docs/en/start/rpc/helloworld.md
- docs/zh/_sidebar.md
- docs/zh/start/rpc/helloworld.md
Fix wrong link
Fixes #
```release-note
```
> doc: Fix wrong link

- configs/runtime_config.json
- docs/zh/start/trace/trace.md
1. reformat runtime_config.json
2. improve metrics document
Fixes #
```release-note
```
> doc: improve metrics doc

- docs/zh/start/istio/start.md
> fix: correct wrong symbols

- .licenserc.yaml
- codecov.yml
- components/lock/consul/consul_lock_test.go
- components/lock/zookeeper/zookeeper_lock_test.go
- components/pkg/mock/consul_mock.go
- components/pkg/mock/zookeeper_mock.go
- components/sequencer/zookeeper/zookeeper_sequencer_test.go
- move components mock file to mock dir
- update license header check and ut check
None
```release-note
```
> feat: improve components mock dir and workflow check

- components/rpc/invoker/mosn/channel/channel.go
- components/rpc/invoker/mosn/channel/httpchannel.go
- components/rpc/invoker/mosn/channel/xchannel.go
If user config the channel listener address with ip address， layotto use net.Dial directly.
Fixes #
```release-note
```
> Split mosn layotto

- README.md
- docs/en/README.md
- docs/zh/README.md
improve readme
Fixes #
```release-note
```
> doc: improve readme

- configs/config_file.json
- demo/file/client.go
- docs/zh/start/file/minio.md
- docs/zh/start/network_filter/tcpcopy.md
- fix minio quickstart
- fix markdown error in tcpcopy quickstart
Fixes #
```release-note
```
> doc: fix minio & tcpcopy quickstart

- configs/config_file.json
- demo/file/client.go
- docs/zh/start/file/minio.md
for more stable demo run, replace official demo with local minio for demo 
Fixes #450 
```release-note
```
> fix: replace official demo with local minio

- cmd/layotto/main.go
- cmd/layotto_multiple_api/main.go
fix: binary file prints wrong information
Fixes #491 
```release-note
```
> fix: binary file prints wrong information

- sdk/go-sdk/client/client.go
- sdk/go-sdk/client/client_test.go
- sdk/go-sdk/client/secret.go
- sdk/go-sdk/client/secret_test.go
add secret client  for go sdk
Fixes #
```release-note
```
> feat: add secret client for go sdk

- README.md
- docs/en/README.md
- docs/zh/README.md
before:
after:
+ add more badges to layotto to show statuses
+ refactor readme layout
> chore: add more badges to layotto and refactor layouts

- docs/zh/development/contributing-doc.md
Improve [document contribution guide](https://mosn.io/layotto/#/zh/development/contributing-doc) so that we don't have to explain the doc site mechanism when reviewing PR.
Fixes #
```release-note
```
> doc: improve document contribution guide

- make/image.mk
push amd64 image should remove suffix
> fix(ci): push amd64 image should remove suffix

- docs/_sidebar.md
- docs/zh/_sidebar.md
docs: fix sidebars for new pages
> docs: fix sidebars for new pages

- docs/zh/start/faas/start.md
fix faas quickstart fails
#520 
I executed it from start to finish, except for a slight modification of the make command, everything is fine, and the final return result is as expected.
> fix: FaaS quickstart fails

- cmd/layotto/main.go
- cmd/layotto_multiple_api/main.go
- make/golang.mk
resolve: https://github.com/mosn/layotto/issues/521
> fix: add version to build flags

- docs/en/start/faas/start.md
resolve: https://github.com/mosn/layotto/issues/533
It seems like that we missed to update the en docs
this is minor :)
> fix:  makefile commands in docs

- pkg/filter/network/tcpcopy/strategy/fuse.go
fix: error format when debugging logs
> fix: error format when debugging logs

- CONTRIBUTING.md
- README.md
- docs/en/README.md
- docs/en/development/CONTRIBUTING.md
- docs/zh/README.md
- docs/zh/development/CONTRIBUTING.md
chore: optimize docs and add more references via new cmds and ci
> chore: optimize docs and add more references via new cmds and ci

- CODE_OF_CONDUCT.md
sync: add code of conduct to meet standards
Github sets some standards for every open source project, add this to improve project scoring.
> sync: add code of conduct to meet standards

- docs/zh/development/test-quickstart.md
- etc/script/test-quickstart.sh
Signed-off-by: seeflood <349895584@qq.com>
improve quickstart contribution guide.
Show steps to add quickstart guide
Fixes #
```release-note
```
> docs: improve quickstart contribution guide

- docs/zh/development/github-workflows.md
Add @Xunzhuo 's video demonstration for layotto workflow
Fixes #
```release-note
```
> docs: add video demonstration for layotto workflow

- docs/zh/design/file/file-design.md
fix a typo which is:
Fixes  #559
> docs(design): fix a typo

- README.md
- docs/en/README.md
- docs/zh/README.md
> docs: add contributors graph

- docs/en/component_specs/secret/common.md
- docs/zh/component_specs/secret/common.md
Fix typo. Change`secretStores` -> `secret_store`
Fixes #
```release-note
```
> docs(secret): `secretStores` -> `secret_store`

- Makefile
- make/ci.mk
- pkg/wasm/abi.go
- sdk/go-sdk/client/secret.go
Fix `make license`.
Currently our license script can't work due to the wrong path 
Fixes #
```release-note
```
> ci: fix license script

- .github/workflows/pr-title-checker.yml
> ci: upgrade title checker

- .github/workflows/pr-title-checker.yml
> chore: fix the CI

- docs/_sidebar.md
- docs/en/operation/README.md
**What this PR does**:  translate the operation guide into english
Fixes #
```release-note
```
> docs(en): add en operation doc

- docs/index.html
- docs/js/pangu.min.js
Import a docsify plugin to automatically add space between chinese and english
Fixes #666 
```release-note
```
> docs: automatically add space between chinese and english

- .gitignore
- docs/zh/community/meeting.md
- docs/zh/community/promote.md
update community doc
Fixes #
```release-note
```
> docs: update community doc

- docs/en/start/faas/start.md
- docs/zh/start/faas/start.md
> fix: deadlinks cause ci failed

- configs/config_ref_example.json
- docs/_sidebar.md
- docs/en/start/secret/secret_ref.md
- docs/zh/_sidebar.md
- docs/zh/start/secret/secret_ref.md
add `secret_ref.md` into sidebar
Fixes #
```release-note
```
> docs: add `secret_ref.md` into sidebar

- docs/zh/development/start-from-zero.md
fix stale contributor guide
Fixes #
```release-note
```
> docs: fix stale contributor guide

- docs/zh/operation/README.md
- docs/zh/operation/local.md
+ docs: add local connect to remote layotto sidecar guide
see https://github.com/mosn/layotto/pull/719
+ docs: fix link from [zh/start] to [zh/start/]
Fixes 
```release-note
```
> docs: add local connect to remote layotto sidecar guide

- demo/deploy/k8s/standalone/default_configmap.yaml
- demo/deploy/k8s/standalone/default_deployment.yaml
- demo/deploy/k8s/standalone/default_quickstart.yaml
Make deploy `layotto` to `k8s` easily.
Fixes https://github.com/mosn/layotto/issues/722
I will update docs.
```release-note
```
> docs: add demo deploy k8s standalone yaml.

- README.md
- docs/en/README.md
fix expired QR code
Fixes #738 
```release-note
```
> docs: fix expired QR code

- docs/zh/_sidebar.md
add oss quickstart into the sidebar
Fixes #
```release-note
```
> docs: add oss quickstart into the sidebar

- docs/zh/_sidebar.md
fix the deadlink in sidebar
Fixes #
```release-note
```
> fix(docs): deadlink in sidebar

- go.mod
- go.sum
upgrade dapr/components-contrib to v1.5.2
Fixes #
```release-note
```
> chore: upgrade components-contrib

- docs/zh/api_reference/how_to_generate_api_doc.md
docs: translate the code-generator guide into chinese; 把代码生成器的使用文档翻译成中文 #797
> docs: translate hot_to_generate_api_doc

- .github/ISSUE_TEMPLATE/good-first-issue-component.md
add an issue template for good first issues
Fixes #
```release-note
```
> chore: add an issue template for good first issues

- .github/ISSUE_TEMPLATE/good-first-issue-component.md
- .github/ISSUE_TEMPLATE/good-first-issue-translate-into-chinese.md
- .github/ISSUE_TEMPLATE/good-first-issue-translate-into-english.md
- .github/ISSUE_TEMPLATE/good-first-issue-ut.md
- components/rpc/invoker/mosn/channel/xchannel.go
add issue templates
Fixes #
```release-note
```
> chore: add issue templates

- make/golang.mk
Signed-off-by: bitliu <bitliu@tencent.com>
Remove go-junit-report since we did not use it.
> chore: remove go.test.verify

- .github/ISSUE_TEMPLATE/good-first-issue-component.md
- .github/ISSUE_TEMPLATE/good-first-issue-java-sdk.md
- .github/ISSUE_TEMPLATE/good-first-issue-js-sdk.md
add templates for sdk good first issues
Fixes #
```release-note
```
> chore: add templates for sdk good first issues

- docs/en/start/faas/start.md
- docs/zh/start/faas/start.md
Update the document  for faas start
Fixes #745
> fix: update document for faas start

- docs/en/start/api_plugin/generate.md
- docs/zh/start/api_plugin/generate.md
improve generator docs
Fixes #
```release-note
```
> docs: improve generator docs

- cmd/layotto/main.go
- cmd/layotto_multiple_api/main.go
- cmd/layotto_without_xds/main.go
> fix: fix pprof

- docs/zh/start/state/start.md
Fixes #855 
```release-note
```
> docs: fix state start api uri

- docs/en/start/api_plugin/generate.md
- docs/zh/start/api_plugin/generate.md
Improve generator docs using [deepL write](https://www.deepl.com/write)
Fixes #
```release-note
```
> docs: improve generator docs using deepL write

- docs/en/development/contributing-doc.md
- docs/en/development/test-quickstart.md
Fix grammar issues using grammarly.
I'm testing grammarly and "deepl write"
Fixes #
```release-note
```
> docs: fix grammar issues using grammarly

- .github/workflows/kube-bot.yaml
ci: add prow bot to manage issues and PRs
@mosn/layotto-commiter @mosn/layotto-pmc 
```release-note
```
> ci: add prow bot to manage issues and PRs

- components/go.mod
- demo/bindings/main.go
- demo/file/client.go
- demo/oss/client.go
Add comments using chatGPT.
This is an experiment.
Fixes #
```release-note
```
> chore: add comments using chatGPT

- .github/workflows/codeql-analysis.yml
- .github/workflows/dead-link-checker.yaml
- .github/workflows/kube-bot.yaml
- .github/workflows/layotto-ci.yml
- .github/workflows/layotto-release.yml
- .github/workflows/license-checker.yml
- .github/workflows/markdown-checker.yml
- .github/workflows/pr-title-checker.yml
- .github/workflows/proto-checker.yml
- .github/workflows/quickstart-checker.yml
- .github/workflows/stale.yml
> chore: clean-up workflows

- components/oss/registry.go
- components/oss/registry_test.go
It's an experiment to generate UT using chatGPT. 
And the generated UT find out a typo:
Fixes #
```release-note
```
> test: add UT and fix a typo using chatGPT

- .github/workflows/kube-bot.yaml
- OWNERS
> ci: update prow bot

- .github/workflows/kube-bot.yaml
> chore: enable debug log

- docs/en/development/component_ref/component_ref.md
> docs: improve doc to test prow bot

- demo/delay_queue/common/client.go
It's an experiment to generate gRPC demo code using chatGPT
Fixes #
```release-note
```
> chore: add demo code for delay queue API, using chatGPT

- .github/workflows/kube-bot.yaml
+ Change schedule time from every 5 minutes to 1 hour, makes it more reliable.
+ Add workflow dispatch trigger.
> feat: change schedule time interval

- .github/workflows/dead-link-checker.yaml
run dead link checker when there are markdown files been modified
Fixes #
```release-note
```
> ci: run dead link checker when there are markdown files been modified

- .github/workflows/cloud_code_scan.yml
- Makefile
> build: 增加tpis

- .github/workflows/sync-to-yuque.yml
> chore: Update sync-to-yuque.yml

- .github/workflows/translate.yml
feat:a feature -feat:xxxxxx featfeatfeat
需要添加token，包括issue和discussion权限
> feat: a feature -feat:xxxxxx featfeatfeat

- .github/workflows/translate.yml
> fix: 修改翻译仓库

- diagnostics/grpc_tracing.go
add NewVariableContext for StreamInterceptorFilter
> feat: add NewVariableContext for StreamInterceptorFilter

- .github/workflows/docusaurus-ci.yml
- docs/algolia-config.json
- docs/crowdin.yaml
- docs/package-lock.json
- docs/package.json
Github Action Bot detected the issue body's language is not English, translate it automatically
---
1, and move the static website to the docs directory
<details><summary>原文</summary>1,统一移动静态网站配置到docs目录</details>
> feat: 1,统一移动静态网站配置到docs目录||feat: 1, Configure the mobile static website to the docs directory 

- .github/workflows/cloud_code_scan.yml
> feat(ci): Add stc scan to cybersec

- pkg/grpc/extension/s3/s3.go
> feat: fix get object empty file

- pkg/grpc/extension/s3/s3.go
> feat: fix oss error

- .github/workflows/layotto-ci.yml
- .github/workflows/layotto-release.yml
> feat(ci): Fix action runner

- components/rpc/invoker/mosn/mosninvoker.go
- components/rpc/invoker/mosn/mosninvoker_test.go
- docs/blog/code/layotto-rpc/index.md
- docs/i18n/en-US/docusaurus-plugin-content-blog/code/layotto-rpc/index.md
feat: add panic stack
```release-note
```
> feat: add panic stack
